package com.lbortolotti.coupon.api.controller.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;

@Schema(name = "Coupon Response",
        description = "Payload sent back by the system with coupon information")
public class CouponResponseDTO {

    @Schema(description = "Unique identifier of the coupon generated by the system.",
        accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(
            description = "Unique code that identifies the coupon.")
    private String code;

    @Schema(description = "Discount percentage applied by the coupon (between 1 and 50).")
    private Integer discount;

    @Schema(description = "Date when the coupon expires. After this date, the coupon is no longer valid.")
    private LocalDate expirationDate;

    public CouponResponseDTO() {}

    public CouponResponseDTO(Long id, String code, Integer discount, LocalDate expirationDate) {
        this.id = id;
        this.code = code;
        this.discount = discount;
        this.expirationDate = expirationDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Integer getDiscount() {
        return discount;
    }

    public void setDiscount(Integer discount) {
        discount = discount;
    }

    public LocalDate getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(LocalDate expirationDate) {
        this.expirationDate = expirationDate;
    }
}
